/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReactRouteImport } from './routes/react'
import { Route as JsRouteImport } from './routes/js'
import { Route as IndexRouteImport } from './routes/index'

const ReactRoute = ReactRouteImport.update({
  id: '/react',
  path: '/react',
  getParentRoute: () => rootRouteImport,
} as any)
const JsRoute = JsRouteImport.update({
  id: '/js',
  path: '/js',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/js': typeof JsRoute
  '/react': typeof ReactRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/js': typeof JsRoute
  '/react': typeof ReactRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/js': typeof JsRoute
  '/react': typeof ReactRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/js' | '/react'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/js' | '/react'
  id: '__root__' | '/' | '/js' | '/react'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JsRoute: typeof JsRoute
  ReactRoute: typeof ReactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/react': {
      id: '/react'
      path: '/react'
      fullPath: '/react'
      preLoaderRoute: typeof ReactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/js': {
      id: '/js'
      path: '/js'
      fullPath: '/js'
      preLoaderRoute: typeof JsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JsRoute: JsRoute,
  ReactRoute: ReactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
